SET IDENTITY_INSERT [dbo].[StoreItems] ON
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (1, N'Bailey''s Comfy Collar', N'Accessory', CAST(8.99 AS Decimal(18, 2)), N'Dog Collar')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (2, N'Flash Collar', N'Accessory', CAST(5.99 AS Decimal(18, 2)), N'Dog Collar')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (3, N'Tinker Bell Collar', N'Accessory', CAST(6.99 AS Decimal(18, 2)), N'Cat Collar')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (4, N'Meow Meow Collar', N'Accessory', CAST(4.99 AS Decimal(18, 2)), N'Cat Collar')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (5, N'Kitty Mix ', N'Pet Food', CAST(14.99 AS Decimal(18, 2)), N'Cat Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (6, N'Organic Cat Mix', N'Pet Food', CAST(23.59 AS Decimal(18, 2)), N'Cat Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (7, N'Ruff Chow', N'Pet Food', CAST(25.99 AS Decimal(18, 2)), N'Dog Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (8, N'Howling Munchies', N'Pet Food', CAST(32.99 AS Decimal(18, 2)), N'Dog Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (9, N'Cat Scratching Post', N'Accessory', CAST(20.59 AS Decimal(18, 2)), N'Cat Life')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (10, N'Cat Pillow Bed', N'Accessory', CAST(12.29 AS Decimal(18, 2)), N'Cat Life')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (11, N'Dog Bed', N'Accessory', CAST(22.69 AS Decimal(18, 2)), N'Dog Life')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (12, N'Dog Auto-Watering Bowl', N'Accessory', CAST(38.49 AS Decimal(18, 2)), N'Dog Life')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (13, N'Aquariuim Sediment', N'Accessory', CAST(12.49 AS Decimal(18, 2)), N'Fish Life')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (14, N'Bag of Filtered Sand', N'Accessory', CAST(8.29 AS Decimal(18, 2)), N'Fish Life')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (15, N'Pirate Ship Alcove prop', N'Accessory', CAST(4.99 AS Decimal(18, 2)), N'Fish Decor')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (16, N'Fake plants (small)', N'Accessory', CAST(3.29 AS Decimal(18, 2)), N'Fish Decor')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (17, N'Fake plants (medium)', N'Accessory', CAST(5.29 AS Decimal(18, 2)), N'Fish Decor')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (18, N'Fake plants (large)', N'Accessory', CAST(7.29 AS Decimal(18, 2)), N'Fish Decor')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (19, N'Tropical Flakes', N'Marine Life', CAST(4.39 AS Decimal(18, 2)), N'Fish Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (20, N'Green Algae Disks', N'Marine Life', CAST(6.25 AS Decimal(18, 2)), N'Fish Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (21, N'Red Tropical Flakes', N'Marine Life', CAST(6.39 AS Decimal(18, 2)), N'Fish Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (22, N'Frozen Brine Shrimp', N'Marine Life', CAST(12.99 AS Decimal(18, 2)), N'Fish Food')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (23, N'German Sheppard', N'Dogs & Cats', CAST(599.59 AS Decimal(18, 2)), N'Live Dog')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (24, N'Golden Retriever', N'Dogs & Cats', CAST(899.99 AS Decimal(18, 2)), N'Live Dog')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (25, N'Elk Hound', N'Dogs & Cats', CAST(1400.89 AS Decimal(18, 2)), N'Live Dog')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (26, N'Persian Cat', N'Dogs & Cats', CAST(160.99 AS Decimal(18, 2)), N'Live Cat')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (27, N'Calico Cat', N'Dogs & Cats', CAST(89.45 AS Decimal(18, 2)), N'Live Cat')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (28, N'American Shorthair', N'Dogs & Cats', CAST(85.99 AS Decimal(18, 2)), N'Live Cat')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (29, N'Swordtail Fish (x5)', N'Marine Life', CAST(12.25 AS Decimal(18, 2)), N'Live Fish (Freshwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (30, N'Black Lined Tetras (x5)', N'Marine Life', CAST(18.99 AS Decimal(18, 2)), N'Live Fish (Freshwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (31, N'Large Angelfish', N'Marine Life', CAST(23.19 AS Decimal(18, 2)), N'Live Fish (Freshwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (32, N'Tiger Oscar (x2)', N'Marine Life', CAST(59.59 AS Decimal(18, 2)), N'Live Fish (Freshwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (33, N'Blue Tang (x2)', N'Marine Life', CAST(85.89 AS Decimal(18, 2)), N'Live Fish (Saltwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (34, N'Oscellaris Clown', N'Marine Life', CAST(23.45 AS Decimal(18, 2)), N'Live Fish (Saltwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (35, N'Foxface Rabbitfish', N'Marine Life', CAST(85.99 AS Decimal(18, 2)), N'Live Fish (Saltwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (36, N'Humu Picasso Triggerfish', N'Marine Life', CAST(160.99 AS Decimal(18, 2)), N'Live Fish (Saltwater)')
INSERT INTO [dbo].[StoreItems] ([Id], [ProductName], [ProductType], [Price], [Descriptor]) VALUES (37, N'Yellow/Black Striped Pilots (x5)', N'Marine Life', CAST(120.99 AS Decimal(18, 2)), N'Live Fish (Saltwater)')
SET IDENTITY_INSERT [dbo].[StoreItems] OFF
